modLoader="javafml"
loaderVersion="[36,)"
license="MIT"
#issueTrackerURL="http://my.issue.tracker/"
[[mods]]
modId="noitawands"
version="${file.jarVersion}"
displayName="NoitaWandsInMinecraft"
#updateJSONURL="http://myurl.me/"
#displayURL="http://example.com/"
#logoFile="noitawands.png"
#credits="Thanks for this example mod goes to Java"
authors="LucunJi"
description='''
Enjoy those wands from Noita!
'''
[[dependencies.noitawands]]
   modId="forge"
   mandatory=true
   versionRange="[36,)"
   ordering="NONE"
   side="BOTH"
[[dependencies.noitawands]]
   modId="minecraft"
   mandatory=true
   versionRange="[1.16.5,1.17)"
   ordering="NONE"
   side="BOTH"
